import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import 'atropos/css'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>      <Navbar/>{children}

<script src="https://kit.fontawesome.com/1dd8f7daa0.js" crossorigin="anonymous"></script>
      </body>
    </html>
  );
}
